### ISSUE TITLE
Variables de entorno en el README

### ISSUE THREAD

**Issue by amgdev9** [Proyecto-FIS/deliveries#22]
Para facilitar el despliegue del microservicio en Kubernetes, sería genial que pusieras en el README.md las variables de entorno que hacen falta con una descripción. También recalcar que todas las URL externas deben estar en variables de entorno.

No hace falta subir el Dockerfile a DockerHub, ya lo hemos hecho.

**Comment by danmarrod** [comment]
Oki, done!
